name: Install and test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        id: cache-node-modules
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.nvmrc
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Check types
        run: yarn tsc
        working-directory: ./frontend

      - name: Run tests
        run: yarn test:coverage
        working-directory: ./frontend

      - name: Check linter
        run: yarn lint
        working-directory: ./frontend
