name: E2E tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        id: cache-node-modules
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.nvmrc
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend

      - name: Archive results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress
          path: |
            /home/runner/work/Geotrek-rando-v3/Geotrek-rando-v3/frontend/cypress/videos/*.mp4
            /home/runner/work/Geotrek-rando-v3/Geotrek-rando-v3/frontend/cypress/screenshots/*.png
